structure(list(method = "GET", url = "https://vginsights.com/api/v3/games/99999999/metadata", 
    status_code = 404L, headers = structure(list(date = "Fri, 08 Aug 2025 02:03:42 GMT", 
        `content-type` = "application/json; charset=utf-8", server = "cloudflare", 
        vary = "Accept-Encoding", vary = "Origin, Accept-Encoding", 
        `access-control-allow-credentials` = "true", `x-ratelimit-limit` = "25", 
        `x-ratelimit-remaining` = "17", `x-ratelimit-reset` = "1754618623", 
        etag = "W/\"62-kSQvbHNznDg0FFQEtkg6/bK+2B8\"", `content-encoding` = "gzip", 
        `cf-cache-status` = "DYNAMIC", nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `report-to` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=tDjIdJKxwUe7xgGGqS4G%2FItU%2Bv5CJpgeWannfMYNHjcrqYmdjsk07idu%2BsHIEbsuWPGTNBI6x7QNI9CHXbYJlD2sR%2B2xjKa59%2BFDjPZI\"}]}", 
        `cf-ray` = "96bb705469b9b79a-ARN", `alt-svc` = "h3=\":443\"; ma=86400"), class = "httr2_headers"), 
    body = charToRaw("{\"message\":\"Game not found\",\"details\":{\"reason\":\"Game with Steam app ID 99999999 was not found.\"}}"), 
    timing = c(redirect = 0, namelookup = 0, connect = 0, pretransfer = 9.3e-05, 
    starttransfer = 0.069907, total = 0.07), cache = new.env(parent = emptyenv())), class = "httr2_response")
