structure(list(method = "GET", url = "https://vginsights.com/api/v3/games/999999999/metadata", 
    status_code = 404L, headers = structure(list(date = "Wed, 07 Oct 2026 08:53:22 GMT", 
        `content-type` = "application/json; charset=utf-8", server = "openresty", 
        `x-frame-options` = "SAMEORIGIN", `x-xss-protection` = "1; mode=block", 
        `x-content-type-options` = "nosniff", `x-download-options` = "noopen", 
        `x-permitted-cross-domain-policies` = "none", `referrer-policy` = "strict-origin-when-cross-origin", 
        `access-control-allow-credentials` = "true", etag = "W/\"63-/P/Bb9P/PSXs2r7OKgziE0P4ucs\"", 
        vary = "Origin, Accept-Encoding", `x-ratelimit-limit` = "25", 
        `x-ratelimit-remaining` = "23", `x-ratelimit-reset` = "1791363203", 
        `x-overseer-info` = "{host: \"app.sensortower.com\", did_call_target_backend: true, target_url: \"https://vgi-production.stinternal.com/api/v3/games/999999999/metadata\", target_status: 404, request_klass: \"ProxiedPlatform::Requests::AuthenticatedRequest\", userid_sent: BSON::ObjectId('63f022fcb3ae27506e3bd949'), target_response_time_in_ms: 37}", 
        `x-api-usage-limit` = "0", `x-api-usage-count` = "393", 
        `cache-control` = "max-age=0, private, must-revalidate", 
        `content-security-policy` = "frame-ancestors 'self' https://*.sensortower.com; frame-src 'self' https://*.sensortower.com https:", 
        `x-request-id` = "6ac60882-584c-2684-251e-74184372213e", 
        traceparent = "00-808ce7efd9072b654172c7d6a60471b1-178450dd09eb0a81-01", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        `content-encoding` = "gzip"), class = "httr2_headers"), 
    body = charToRaw("{\"message\":\"Game not found\",\"details\":{\"reason\":\"Game with Steam app ID 999999999 was not found.\"}}"), 
    timing = c(redirect = 0, namelookup = 0, connect = 0, pretransfer = 8.2e-05, 
    starttransfer = 0.225298, total = 0.231782), cache = new.env(parent = emptyenv())), class = "httr2_response")
